name: app_quizz_score_avec_leaderboard
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  audioplayers: ^6.1.2
  percent_indicator: ^4.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animate_do: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videogame.mp3
    - assets/winning.mp3
